/**
 * GitHub source-control / CI configuration contract (Work Order P3).
 *
 * GitHub carries source control, project state and CI. The contract fixes:
 *
 *   - the variable names the GitHub adapter and webhook verification read
 *     (GITHUB_ACCESS_TOKEN, GITHUB_WEBHOOK_SECRET — both SECRET);
 *   - the CI topology contract: GitHub auto-discovers workflows ONLY at
 *     .github/workflows/*.yml (top level); deployment definitions live
 *     under .github/workflows/deployment/** and are invoked by THIN
 *     top-level callers. The frozen .github/workflows/verify.yml is never
 *     modified by productization waves (W0-W18 freeze);
 *   - repository operations happen through the GitHub adapter (an
 *     adapter, never a semantic authority — spec/architecture rule).
 *
 * Pure data + pure functions; no process.env, no network, no clock.
 */

import { InfraDeploymentError } from '../core/types.ts';

/** The repository-relative workflow roots this contract owns/documents. */
export const GITHUB_WORKFLOW_ROOT = '.github/workflows';
export const GITHUB_DEPLOYMENT_WORKFLOW_DIR = '.github/workflows/deployment';
export const GITHUB_FROZEN_WORKFLOWS = ['.github/workflows/verify.yml'] as const;

/** The CI topology contract (machine-checkable, documented). */
export const GITHUB_CI_TOPOLOGY_CONTRACT = {
  provider: 'github',
  autoDiscovery:
    'GitHub auto-discovers workflows only at .github/workflows/*.yml (top level); nested directories are NOT auto-discovered',
  thinCallerRule:
    'top-level deployment workflow files must be THIN callers that delegate to reusable/composite definitions under .github/workflows/deployment/**',
  frozenWorkflows: 'the existing .github/workflows/verify.yml is frozen W0-W18 output and is never modified',
  offlineRule:
    'deployment contract verification runs offline in CI: it verifies CONTRACTS (schema, policy, isolation, sanity, revision shape) — not deployments — and needs no credentials',
  secretRule: 'CI failures report variable NAMES and pattern ids, never values',
} as const;

/** The variables consumed by the GitHub provider adapters. */
export const GITHUB_VARIABLES = {
  accessToken: 'GITHUB_ACCESS_TOKEN',
  webhookSecret: 'GITHUB_WEBHOOK_SECRET',
} as const;

/**
 * Validates that a workflow path declared by later configuration is either
 * a thin top-level caller or lives under the deployment definitions root.
 * Frozen workflow paths are rejected as modification targets.
 */
export function assertValidWorkflowPath(workflowPath: string): void {
  if ((GITHUB_FROZEN_WORKFLOWS as readonly string[]).includes(workflowPath)) {
    throw new InfraDeploymentError(
      `workflow path '${workflowPath}' is frozen W0-W18 output and must not be modified or generated by productization work`,
    );
  }
  const topLevel = /^\.github\/workflows\/[^/]+\.yml$/.test(workflowPath);
  const deploymentDir = workflowPath.startsWith(`${GITHUB_DEPLOYMENT_WORKFLOW_DIR}/`);
  if (!topLevel && !deploymentDir) {
    throw new InfraDeploymentError(
      `workflow path '${workflowPath}' must be a top-level thin caller (.github/workflows/<name>.yml) or a definition under ${GITHUB_DEPLOYMENT_WORKFLOW_DIR}/`,
    );
  }
}

/** Regions (GitHub is global; the contract records one symbolic region). */
export const GITHUB_REGIONS = ['global'] as const;
export type GitHubRegion = (typeof GITHUB_REGIONS)[number];
export const GITHUB_DEFAULT_REGION: GitHubRegion = 'global';
